name: Filter M3U Playlist

on:
  schedule:
    # Run this workflow every day at midnight
    - cron: '0 0 * * *'

  workflow_dispatch:  # This allows manual triggering of the workflow
    inputs:
      reason:
        description: 'Reason for manually running the workflow'
        required: false
        default: 'Manual run'

jobs:
  filter-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script to filter the M3U playlist
      run: python filter_playlist.py

    - name: Commit filtered playlist
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ita.m3u
        git commit -m "Update filtered M3U playlists"
        git push
